repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        args: [-c, .markdownlint.yaml, --fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint

  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.9.0.2
  #   hooks:
  #     - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.6.0-1
    hooks:
      - id: shfmt
        args: [-w, -s, -i=4]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=120

  # - repo: https://github.com/pycqa/flake8.git
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       args:
  #         - --max-line-length=120

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.2
    hooks:
      - id: hadolint
        files: docker/Dockerfile*
        args:
          [
            --ignore,
            DL3006,
            --ignore,
            DL3008,
            --ignore,
            DL3013,
            --ignore,
            SC2016,
            --ignore,
            SC1091,
            --ignore,
            DL3059,
          ]
