_base_: encdec_exp002.yaml

# data
start_channels: 24
in_channels: 16
patch_size: 224
stride: 112
batch_size: 16
norm_mean: 0.45
norm_std: 0.225

train_augmentations:
  - type: HorizontalFlip
    p: 0.5
  - type: VerticalFlip
    p: 0.5
  - type: RandomBrightnessContrast
    p: 0.75
  - type: ShiftScaleRotate
    p: 0.75
  - type: OneOf
    transforms:
      - type: GaussNoise
      - type: GaussianBlur
      - type: MotionBlur
    p: 0.4
  - type: GridDistortion
    p: 0.5
  - type: CoarseDropout
    p: 0.5
    max_holes: 1
    max_width: 0.3
    max_height: 0.3
    mask_fill_value: 0

# model
model_name: Enc3dDec2d
encoder_name: swin3d_t
model_params:
  decoder_type: mlp
  decoder_patch_expand_channel_scale: 1
  decoder_logit_interpolate_upscale_factor: 2
optimizer_name: AdamW
scheduler_name: GradualWarmupSchedulerV2
losses:
  - type: SoftBCEWithLogitsLoss

head_init_weights: xavier_uniform_
head_init_bias: 0.0

epochs: 15
